apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: spec_project
  title: Spec Project
  description: Kong/Kubernetes Artifacts generator via Spec
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform-templates
    - kong
    - kubernetes
    - bitbucket
spec:
  owner: veecode/platform
  type: devops
  parameters:  
    ### Project Configuration
    - title: Catalog Details
      required:
        - componentId
        - owner
      properties:
        componentId:
          title: Project name
          type: string
          description: Name of the project. ex Viacep_app.
          pattern: '^([a-z0-9]|[.]|[_]|[-])*$'
          ui:autofocus: true
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          ui:widget: textarea
          ui:options:
            rows: 1
          description: Tell us more about your project
          default: "Artifacts generator via Spec."
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              
    ### Spec Configuration
    - title: Spec Configuration
      required:
        - inputspec
      properties:
        inputspec:
          title: Input Spec
          description: Insert Spec
          type: string
          ui:widget: textarea
          ui:autofocus: true
          ui:placeholder: |
          
            apiVersion: backstage.io/v1alpha1
              kind: Component
              metadata:
                name: backstage
              spec:
                type: library
                owner: CNCF
                lifecycle: experimental
          ui:options:
            rows: 20
             
    ### Location Configuration
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Choose a location to create the Access Stack Pipeline
          ui:field: RepoUrlPlatform
          ui:options:
            allowedHosts:
              - bitbucket.org
            allowedOwners:
              - credmais
            allowedProjects:
              - BAC
        visibility:
          title: Repository visibility
          type: string
          enum:
            - public
            - private
          enumNames:
            - 'Public'
            - 'Private'
          default: private
          
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton      
        values:
          componentId: ${{ parameters.componentId }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          #Spec configuration
          inputspec: ${{ parameters.inputspec}}
          #location configuration      
          repoUrl: ${{ parameters.repoUrl | parseRepoUrl | pick('workspace') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          host: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}
          
  
    - id: publish
      name: Publish in Bitbucket
      action: publish:bitbucketCloud
      input:
        allowedHosts:
          - bitbucket.org
        description: This is ${{ parameters.componentId }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.visibility }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml